# Generated by Django 4.0.3 on 2022-04-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_electr', '0002_Cambios_Pedido_Model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numeroDocumentoCliente',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipoDocumentoCliente',
            field=models.CharField(choices=[['RUC', 'RUC'], ['DNI', 'DNI']], max_length=5, null=True),
        ),
    ]
